### ISSUE TITLE
Tic Tac Toe Interface

### ISSUE THREAD

**Issue by jessebelcourt** [TorrenceB/tic-tac-toe#2]
# Summary

We need a tic tac toe web interface. We need a tic tac toe board, we need a scoreboard with players and associated scores. We buttons for 'restart', and for 'play again'. We need a message for which player won. We need a modal for making sure they wanted to 'restart'.

- [x] Tic Tac Toe board
- [x] Scoreboard for players
- [x] Restart button
- [x] Play Again button
- [x] Winner Message (modal?)
- [x] Validation message for restarting

**Comment by TorrenceB** [comment]
@jessebelcourt You wanna take a look at my progress so far mang?

**Comment by TorrenceB** [comment]
@jessebelcourt Check out/compare the last two commits particularly with my board component. I pushed to the feature/interface branch

**Comment by jessebelcourt** [comment]
Decided to use 'alerts' instead of modals initially. Can circle back around.

**Comment by jessebelcourt** [comment]
done.

**Comment by TorrenceB** [comment]
Done. Merged into develop.
